name: Block merges for EOL

on: pull_request


jobs:
  block-merges-eol:
    name: Test
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test"
        run: |
          echo "${{ github.ref_name }}"" | echo ${{ github.head_ref  }}"
